### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by cavemanloverboy** [libjxl/jxl-rs#6]
Can we get a bit more documentation on the state of this rust impl. I may have some free time to contribute here and there but have no idea about the state of things.

**Comment by veluca93** [comment]
Hi!
I don't have so much time to contribute to this project anymore, but I'd be willing to help you along with it :)
Would you be willing to have a short call on the topic, or do you prefer other means of communication?

**Comment by veluca93** [comment]
See #58
